[[language]]
name = "erlang"
# scope = "source.erlang"
# injection-regex = "erl(ang)?"
# file-types = ["erl", "hrl", "app", { glob = "rebar.config" }, { glob = "rebar.lock" }, { glob = "*.app.src" }]
# roots = ["rebar.config"]
# shebangs = ["escript"]
# comment-token = "%%"
# indent = { tab-width = 4, unit = "    " }
language-servers = ["elp"]

[language-server.elp]
command = "elp"
args = ["server"]
